In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1+a2

array([ 7,  9, 11, 13, 15])

In [3]:
a1 // a2

array([0, 0, 0, 0, 0])

In [4]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

2. Broadcasting

In [5]:
ls = [10,20,30,40,50]
arr = np.array(ls)

In [6]:
arr + 10

array([20, 30, 40, 50, 60])

3. Shallow Copy

In [7]:
b = ls.copy()
b

[10, 20, 30, 40, 50]

In [8]:
b[1] = 100
ls

[10, 20, 30, 40, 50]

In [9]:
# Deep Copy
# b = ls

4. Matrox Operation

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [14]:
A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [15]:
A @ B

array([[19, 22],
       [43, 50]])

In [16]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [20]:
# Transpose matrix
A.T

array([[1, 3],
       [2, 4]])

5. Advance array manipulation

In [23]:
# Staking array
a1, a2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [25]:
np.vstack((a1,a2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
np.hstack((a1,a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.column_stack((a1,a2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [31]:
# Splitting Array

c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [35]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]