In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,"Hell0"])
arr

array(['1', '2', '3', '4', '5', 'Hell0'], dtype='<U21')

In [3]:
ls = [[1,2,3],[4,5,6],[7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(ls) # 2D Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr = np.linspace(1,20,5)

In [30]:
arr

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

2. Random Generation Function

In [33]:
np.random.rand(5)

array([0.34364284, 0.60414302, 0.44530707, 0.52573205, 0.139752  ])

In [38]:
np.random.randint(4)

2

In [44]:
np.random.randint(5,10,2)

array([5, 9], dtype=int32)


3. Array Attributes

In [47]:
arr = np.array(ls)

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr.shape

(3, 3)

In [50]:
arr.size

9

In [51]:
arr.dtype

dtype('int64')

4. Array Methods

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.min()

np.int64(1)

In [54]:
arr.max()

np.int64(9)

In [55]:
arr.sum()

np.int64(45)

In [59]:
colsum = np.sum(arr, axis=1)
colsum

array([ 6, 15, 24])

In [60]:
rowsum = np.sum(arr, axis=0)
rowsum

array([12, 15, 18])

In [61]:
arr.mean()

np.float64(5.0)

In [62]:
arr.std()

np.float64(2.581988897471611)

In [68]:
arr.argmax()

np.int64(8)

4. Reshaping & Resizing

In [77]:
arr = np.arange(1,41)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [81]:
arr = arr.reshape(5,8)

In [82]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

5. Indexing and Slicing

In [84]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [85]:
arr[0,0]

np.int64(1)

In [86]:
arr[0,4]

np.int64(5)

In [88]:
arr[5,4] #1. Rows 2. Columns

np.int64(30)

In [89]:
# Slicing
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [91]:
slice = arr[3:, 3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

6. Boolean Indexing

In [99]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
bool = arr % 2 == 0
bool

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [101]:
arr = arr[bool]

In [102]:
arr

array([ 2,  4,  6,  8, 10])